baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Abby Black Art'


[params]

[[params.menu]]
name = "2D"
url =  "/2d"

[[params.menu]]
name = "3D"
url = "/3d"

[[params.menu]]
name = "About/CV"
url = "/about"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'